galaxy_info:
  author: Houcem KHLIFI
  description: Role simple pour installer et configurer Apache
  company: Logwire Consulting
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions: [20.04, 22.04]
dependencies: []
